# Generated by Django 5.2 on 2025-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_enquiry_table_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_table',
            name='dropdown',
            field=models.CharField(max_length=100),
        ),
    ]
